services:
  dfe.managefreeschoolprojects:
    environment:
      Mfsp__ApiEndpoint: "http://dfe.managefreeschoolprojects.api:3000" 
    image: ${DOCKER_REGISTRY-}dfemanagefreeschoolprojects
    build:
      context: .
      dockerfile: Dfe.ManageFreeSchoolProjects/Dockerfile
    ports:
       - 5001:5001
       - 5000:5000
    networks:
      - local-dev
 
  dfe.managefreeschoolprojects.api:
    environment:
      ConnectionStrings__DefaultConnection: "Server=${MSFPDB_DB_SERVER};Database=mfspdb;User Id=sa;Password=${MSFPDB_SA_PASSWORD};TrustServerCertificate=true"
    image: ${DOCKER_REGISTRY-}dfemanagefreeschoolprojects.api
    build:
      context: .
      dockerfile: Dfe.ManageFreeSchoolProjects.API/Dockerfile
    ports:
       - 3001:3001
       - 3000:3000
    networks:
      - local-dev

networks:
  local-dev: