services:     
   mfspsqldb:
    image: mcr.microsoft.com/azure-sql-edge:latest@sha256:902628a8be89e35dfb7895ca31d602974c7bafde4d583a0d0873844feb1c42cf
    environment:
      ACCEPT_EULA: Y
      MSSQL_SA_PASSWORD: mySuperStrong_pa55word!!!
    ports:
      - "1433:1433"
    networks:
      - local-dev
    healthcheck:
      test: /opt/mssql-tools/bin/sqlcmd -S 127.0.0.1 -U sa -P mySuperStrong_pa55word!!! -C -Q 'SELECT 1' || exit 1
      interval: 2s
      retries: 10
    restart: always 

   mfspsqldb.configurator:
    image: mcr.microsoft.com/mssql/server:2022-latest@sha256:0ec7739e1c5ec2f57861facbe1f2b74f1d3e147c7c97edf91eeea920c5944d9c
    volumes:
      - ./init:/initdb.d
    networks:
      - local-dev
    depends_on:
      mfspsqldb:
        condition: service_healthy
    command: >
      bash -c '
      /opt/mssql-tools18/bin/sqlcmd -S mfspsqldb -U sa -P mySuperStrong_pa55word!!! -C -d master -i initdb.d/init-sqldatabase.sql;
      echo "All done!";
      '

   dfe.managefreeschoolprojects.datamigration: 
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - CONNECTION_STRING=Server=host.docker.internal,1433;Database=mfspdb;User Id=sa;Password=mySuperStrong_pa55word!!!;TrustServerCertificate=True
    build:
        context: ../Dfe.ManageFreeSchoolProjects
        dockerfile: Dfe.ManageFreeSchoolProjects.Data/Dockerfile
    depends_on:
         mfspsqldb.configurator:
            condition: service_completed_successfully
    networks:
      - local-dev
      
networks:
  local-dev:
    
